### ISSUE TITLE
JWT claim-based authorization vault/bucket/role setup MinIO+AWS aka. Role Chaining

### ISSUE THREAD

**Issue by chenkins** [shift7-ch/katta-server#10]
### Story
* **Persona**: dev/ops/sec
* **Need**: only create roles at hub setup time AWS-side
* **Purpose**: prevent role escalation / [complexity kills security](https://www.schneier.com/essays/archives/1999/11/a_plea_for_simplicit.html)

### Acceptance Criteria
- [x] finalize bucket naming convention --> implementation in shift7-ch/katta-server#15 
- [x] ~where to store vaults in Keycloak: use user attribute or roles....? If user attribute `vault` instead of `vaults`~
- [x] cleanup `dev-realm.json` 
  - [x] re-use `cryptomator` client id to for cipherduck, see discussion shift7-ch/katta-server#6,  minimal diff to upstream
  - [x] apply same setup in staging Keycloak
   - [x] more transparency in keycloak configs for integration tests and local runs with password grant - can we do without duplicating the config?
  - [x] what about `user001` in `dev-realm.json`? Add it on the fly for integration tests?
  - [x] syncer should not have full admin role in `dev-realm.json`
- [x] Documentation `aud` etc.
- [x] ~~proper solution to allow `AssumeRoleWithWebIdentity` if no vault is shared with us.~~ -> not required if we go for shift7-ch/katta-clientlib#30 
  - [x] ~~MinIO setting~~
  - [x] ~~AWS setting~~ 
- [x] Document design decision and considered alternatives
- [x] Custom mapper AWS
- [x] AWS/MinIO switch (which mapper -> already UMA?)
- [x] frontend implementation create bucket AWS + MinIO using AssumeRoleWithWebIdentity shift7-ch/katta-server#3 
- [x] implementation chained assume role in cyberduck/client
- [x] documenation OIDC + bucket creation role + role chaining roles shift7-ch/katta-server#23 

### Open Questions
* when to switch from user attributes to resources (#41)? Start implementation with user attributes. 

### Context
* Depends on/relates to shift7-ch/katta-server#6.
* Preparations for shift7-ch/katta-clientlib#30 shift7-ch/katta-server#3 shift7-ch/katta-clientlib#94
* Prerequisite for shift7-ch/katta-server#41
