### ISSUE TITLE
[Story] Scoped Access Tokens through Authorization Services / UMA

### ISSUE THREAD

**Issue by chenkins** [shift7-ch/katta-server#41]
### Story
* **Persona**: user of Cipherduck
* **Need**: scoped token
* **Purpose**: not be restricted in the number of vaults and configured storage backends

### Acceptance Criteria
- [ ] ~implement patch https://github.com/keycloak/keycloak/issues/22096~
- [ ] ~move from user attributes (#10) to authorization resources in Keycloak~
- [ ] ~distribution of client secret?~
- [ ] ~client secret in client~
- [x] implement ~UMA~ token-exchange call client-side: use access token instead of id token
- [x] opt. implement ~UMA~ token-exchange call hub-side for bucket creation as well (see https://github.com/cryptomator/hub/issues/206)
- [ ] ~containerize minio test~ -> shift7-ch/katta-clientlib#94 
- [x] test keychain multiple vaults with token-exchange
- [x] test session lifetimes, first implementation does token-exchange immediately
- [x] staging+AWS with token-exchange -> requires instance with token-exchange feature
- [x] config from hub
- [x] finalize documentation: decision, ER diagram, how many token exchanges?
- [x] check on backup strategy of resources data in Keycloak
- [x] cleanup `dev-realm.json`: which claim is required in hub for user role etc.? As users get one role per shared vault, this should not grow in access token!
- [x] cleanup `dev-realm.json` clients `cryptomatorvaults` and `realm-management`
- [x] remove client roles from access token or implement token exchange before STS bucket creation in frontend.

### Open Questions
* ~Closer look at UMA data model and API to create resources, permissions, authorization scopes, authorization policies... tentatively:~
  *   ~1 Authorization Resource per Vault (has an associated Authorization Scope)~
  *  ~1 Authorization Policy per Vault: which users?~
  *  ~1 Authorization Policy per vault~
  *  ~1 Authorization Scope per backend type~
  *  ~1 resource-based permission per vault: links resource and policy~

### Context
* ~Some lock-in to Keycloak and status of UMA specification deemed acceptable~
* continuation of shift7-ch/katta-server#10 to solve token size problem (scoped tokens)
* ~open discussion whether Keycloak authorization/permission should be the main source of truth for vault access management in hub~
